version: "3"
services:
  rabbitmq:
    image: 'registry.ucoder.ir/rabbitmq:3-management'
    ports:
      - "15672:15672"
  jupyter:
    image: 'quay.io/arcana261/messaging_workshop'
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/opt/notebooks"
      - "./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py"
